pipeline {
    agent any

    options {
        skipDefaultCheckout()
    }

    environment {
        DOCKER_IMAGE = 'prajwalbambulkar/3tiernodejs'
        IMAGE_TAG = "frontend-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout changelog: true, poll: true,scm: scm
            }
        }

        stage('Verify Changes in Frontend Folder') {
            when {
                changeset "frontend/**"
            }
            steps {
                echo "✅ Detected changes in frontend folder."
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "frontend/**"
            }
            steps {
                dir('frontend') {
                    script {
                        echo "🚧 Building Docker image: ${DOCKER_IMAGE}:${IMAGE_TAG}"
                        docker.build("${DOCKER_IMAGE}:${IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            when {
                changeset "frontend/**"
            }
            steps {
                dir('frontend') {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', '03b85bf0-3391-428c-bd80-0fce51e052b5') {
                            docker.image("${DOCKER_IMAGE}:${IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Frontend CI pipeline completed successfully. Image: ${DOCKER_IMAGE}:${IMAGE_TAG}"
        }
        failure {
            echo '❌ Frontend CI pipeline failed.'
        }
    }
}
